version: "3.8"
services:
  movies:
    image: sairohitchinta/movies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
        
  trains:
    image: sairohitchinta/trains:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
        
  recharge:
    image: sairohitchinta/recharge:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
        
  dth:  
    image: sairohitchinta/dth:latest
    ports:
      - 84:80
    deploy:
      replicas: 3